### PR TITLE
Completed css-brochure-exercise-Chris Mendozas

### PR DESCRIPTION
**Pull request by CTMendoza**
CSS-Brochure

### CODE REVIEW

**Review by Zhiwutian — CHANGES_REQUESTED** [review]
Great initial submission! Now its about the details:
1. take a look at the vertical distance for the inputs
2. the roundness of the inputs edges
3. The size of the text on the submit button

Now that you have the HTML and CSS foundation, hit those last details to make yours match the example. Great work so far!

**Comment by CTMendoza** [comment]
CSS-Brochure

**Comment by CTMendoza** [comment]
CSS-Brochure

**Comment by CTMendoza** [comment]
Oops wrong one.

CSS-Brochure

**Review by Zhiwutian — APPROVED** [review]
👍🏼

**Pull request merged**
